# Swift/iOS Project Code Review Template
# Copy this file to .github/workflows/ai-code-review.yml in your repository

name: AI Code Review for Swift/iOS

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.swift'
      - '**.h'
      - '**.m'
      - '**/project.pbxproj'
      - '**/*.storyboard'
      - '**/*.xib'

jobs:
  review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Get PR diff
        id: diff
        run: |
          git diff origin/${{ github.base_ref }}...HEAD > pr_diff.txt
          DIFF_SIZE=$(stat -c%s pr_diff.txt 2>/dev/null || stat -f%z pr_diff.txt)
          if [ "$DIFF_SIZE" -gt 100000 ]; then
            echo "PR diff is too large for review (>100KB)" > pr_diff.txt
          fi
          
      - name: AI Code Review - Swift/iOS Focus
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          PR_DIFF=$(cat pr_diff.txt | head -c 50000)
          
          REQUEST_BODY=$(jq -n \
            --arg diff "$PR_DIFF" \
            '{
              "model": "claude-3-opus-20240229",
              "max_tokens": 4096,
              "messages": [{
                "role": "user",
                "content": "You are reviewing a Swift/iOS project. Please analyze the following code changes with special attention to:\n\n1. **Swift-specific issues:**\n   - Optional handling and force unwrapping\n   - Memory management (retain cycles, weak/unowned usage)\n   - Protocol conformance and extensions\n   - Value vs Reference type usage\n   - Swift naming conventions\n\n2. **iOS/UIKit/SwiftUI concerns:**\n   - Main thread UI updates\n   - Auto Layout constraints\n   - View lifecycle management\n   - iOS version compatibility\n   - App lifecycle and state management\n\n3. **Performance:**\n   - Collection operations efficiency\n   - Image and resource loading\n   - Network request handling\n   - Core Data/database queries\n\n4. **Security:**\n   - Keychain usage\n   - Data encryption\n   - URL scheme handling\n   - Privacy and permissions\n\n5. **Testing:**\n   - Unit test coverage\n   - UI test scenarios\n   - Mock objects usage\n\nProvide specific Swift code examples for improvements.\n\nPR Diff:\n\n\($diff)"
              }]
            }')
          
          REVIEW_RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" https://api.anthropic.com/v1/messages \
            -H "x-api-key: $ANTHROPIC_API_KEY" \
            -H "anthropic-version: 2023-06-01" \
            -H "content-type: application/json" \
            -d "$REQUEST_BODY")
          
          HTTP_STATUS=$(echo "$REVIEW_RESPONSE" | grep "HTTP_STATUS" | cut -d: -f2)
          RESPONSE_BODY=$(echo "$REVIEW_RESPONSE" | sed '/HTTP_STATUS/d')
          
          if [ "$HTTP_STATUS" -ne 200 ]; then
            echo "API call failed (Status: $HTTP_STATUS)" > review_comment.txt
            echo "$RESPONSE_BODY" >> review_comment.txt
          else
            REVIEW_CONTENT=$(echo "$RESPONSE_BODY" | jq -r '.content[0].text // "Unable to generate review"')
            echo "$REVIEW_CONTENT" > review_comment.txt
          fi
          
      - name: Post review comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const reviewContent = fs.readFileSync('review_comment.txt', 'utf8');
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `## 🍎 AI Code Review for Swift/iOS\n\n${reviewContent}\n\n---\n*Specialized review for Swift/iOS best practices by Claude 3 Opus*`
            });